<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SameerJ" failures="1" tests="1" name="com.inetbanking.runner.TestRunnerAddingCustomer" time="9.018" errors="0" timestamp="2021-08-27T12:24:21 IST" skipped="0">
  <testcase classname="com.inetbanking.runner.TestRunnerAddingCustomer" name="runScenario" time="9.018">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.inetbanking.testCases.Customer_Add_BDD_002.manager_verify_cutomer_is_added_or_not(Customer_Add_BDD_002.java:106)
at âœ½.manager verify cutomer is added or not(file:///C:/SAMEER/inetBanking/src/test/resources/Features/custAdd.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.inetbanking.runner.TestRunnerAddingCustomer -->
